steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['verify', '-DskipTests', '-f', 'pom_quarkus.xml']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile_quarkus.jvm', '-t', 'gcr.io/$PROJECT_ID/randomstrings-quarkus', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/randomstrings-quarkus' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'randomstrings-quarkus'
      - '--image'
      - 'gcr.io/$PROJECT_ID/randomstrings-quarkus:latest'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
images: ['gcr.io/$PROJECT_ID/randomstrings-quarkus']